#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
$dotenv = \Dotenv\Dotenv::createImmutable(__DIR__ . '/');
$dotenv->load();

$container = require_once __DIR__.'/config/container.php';
/** @var Application $application */
$application = $container->get(Application::class);

// ... register commands
$application->add(new \App\Commands\TestCommand($container));
$application->add(new \App\Commands\CreateUserCommand($container));

$application->run();
