version: '3.6'
services:

  #PHP Service
  city-quest_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: city-quest_api
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  nginx_city-quest_api:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - 8081:80/tcp
      - 444:443/tcp
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d

  #MySQL Service
  db_city-quest_api:
    image: mysql:5.7.22
    restart: always
    tty: true
    ports:
      - 3001:3306/tcp
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - default

  phpmyadmin_city-quest_api:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8091:80/tcp
    links:
      - city-quest_api
    environment:
      PMA_HOST: ${PMA_HOST}

